# Generated by Django 5.2.15 on 2026-06-08 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4Subnet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cidr', models.CharField(max_length=43)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('dns_servers', models.JSONField(blank=True, default=list)),
                ('default_lease_time_seconds', models.PositiveIntegerField(default=43200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site__name', 'cidr'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DHCPPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('end_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('lease_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_pools', to='ipam.ipv4subnet')),
            ],
            options={
                'ordering': ['subnet__cidr', 'start_ip'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='ipam.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ipv4subnet',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipv4_subnets', to='ipam.site'),
        ),
        migrations.CreateModel(
            name='DHCPReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=253)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_reservations', to='ipam.ipv4subnet')),
            ],
            options={
                'ordering': ['subnet__cidr', 'ip_address'],
                'constraints': [models.UniqueConstraint(fields=('subnet', 'ip_address'), name='unique_reservation_ip_per_subnet')],
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_site_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='ipv4subnet',
            constraint=models.UniqueConstraint(fields=('site', 'cidr'), name='unique_ipv4_subnet_cidr_per_site'),
        ),
    ]
