# Generated by Django 5.2.15 on 2026-06-11 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('validation_failed', 'Validation failed'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('source_kind', models.CharField(default='manual', max_length=32)),
                ('change_summary', models.TextField(blank=True)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('rendered_files', models.JSONField(blank=True, default=dict)),
                ('artifact_manifest', models.JSONField(blank=True, default=dict)),
                ('artifact_hash', models.CharField(blank=True, max_length=64)),
                ('artifact_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_config_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_config_versions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_versions', to='ipam.site')),
            ],
            options={
                'ordering': ['site__organization__name', 'site__name', '-version_number'],
                'constraints': [models.UniqueConstraint(fields=('site', 'version_number'), name='unique_config_version_number_per_site')],
            },
        ),
    ]
