from __future__ import annotations

import pytest

from managed_dhcp_server.configs.renderer import (
    RENDERED_FILE_PATHS,
    build_artifact_manifest,
    compute_artifact_hash,
    render_site_dnsmasq_config,
    sha256_text,
)

from .helpers import create_pool, create_reservation, create_site, create_subnet


pytestmark = pytest.mark.django_db


def test_render_empty_site_returns_all_files_with_headers() -> None:
    site = create_site("render-empty")

    files = render_site_dnsmasq_config(site)

    assert sorted(files) == sorted(RENDERED_FILE_PATHS)
    for content in files.values():
        assert content.startswith("# Generated by Managed DHCP/IPAM Control Plane.\n# Do not edit manually.\n")
        assert "# Site: render-empty\n" in content


def test_render_enabled_pool_into_ranges_file() -> None:
    site = create_site("render-pool")
    subnet = create_subnet(site, "192.168.10.0/24")
    create_pool(subnet, start_ip="192.168.10.100", end_ip="192.168.10.150")

    files = render_site_dnsmasq_config(site)

    assert (
        "dhcp-range=set:subnet-192-168-10-0-24,192.168.10.100,192.168.10.150,255.255.255.0,43200s"
        in files["dnsmasq/10-ranges.conf"]
    )


def test_disabled_pool_is_skipped() -> None:
    site = create_site("render-disabled-pool")
    subnet = create_subnet(site)
    pool = create_pool(subnet)
    pool.enabled = False
    pool.full_clean()
    pool.save()

    files = render_site_dnsmasq_config(site)

    assert "dhcp-range=" not in files["dnsmasq/10-ranges.conf"]


def test_render_gateway_and_dns_servers_into_options_file() -> None:
    site = create_site("render-options")
    create_subnet(site, "192.168.10.0/24")

    files = render_site_dnsmasq_config(site)

    assert "dhcp-option=tag:subnet-192-168-10-0-24,option:router,192.168.10.1" in files["dnsmasq/20-options.conf"]
    assert "dhcp-option=tag:subnet-192-168-10-0-24,option:dns-server,192.168.10.1,8.8.8.8" in files["dnsmasq/20-options.conf"]


def test_render_enabled_reservation_and_host_record() -> None:
    site = create_site("render-reservation")
    subnet = create_subnet(site)
    create_reservation(subnet, mac_address="AA-BB-CC-DD-EE-FF")

    files = render_site_dnsmasq_config(site)

    assert (
        "dhcp-host=aa:bb:cc:dd:ee:ff,set:subnet-192-168-10-0-24,192.168.10.42,printer-1,infinite"
        in files["dnsmasq/30-reservations.conf"]
    )
    assert "address=/printer-1/192.168.10.42" in files["dnsmasq/40-hosts.conf"]


def test_disabled_reservation_is_skipped() -> None:
    site = create_site("render-disabled-reservation")
    subnet = create_subnet(site)
    reservation = create_reservation(subnet)
    reservation.enabled = False
    reservation.full_clean()
    reservation.save()

    files = render_site_dnsmasq_config(site)

    assert "dhcp-host=" not in files["dnsmasq/30-reservations.conf"]
    assert "address=/" not in files["dnsmasq/40-hosts.conf"]


def test_rendering_is_deterministic_and_sorted() -> None:
    site = create_site("render-deterministic")
    subnet_b = create_subnet(site, "192.168.20.0/24", name="B")
    subnet_a = create_subnet(site, "192.168.10.0/24", name="A")
    create_pool(subnet_b, start_ip="192.168.20.120", end_ip="192.168.20.150")
    create_pool(subnet_a, start_ip="192.168.10.100", end_ip="192.168.10.120")
    create_reservation(subnet_b, hostname="beta", mac_address="aa:bb:cc:dd:ee:20", ip_address="192.168.20.42")
    create_reservation(subnet_a, hostname="alpha", mac_address="aa:bb:cc:dd:ee:10", ip_address="192.168.10.42")

    first = render_site_dnsmasq_config(site)
    second = render_site_dnsmasq_config(site)

    assert first == second
    ranges = first["dnsmasq/10-ranges.conf"]
    reservations = first["dnsmasq/30-reservations.conf"]
    assert ranges.index("192.168.10.100") < ranges.index("192.168.20.120")
    assert reservations.index("192.168.10.42") < reservations.index("192.168.20.42")


def test_file_hashes_are_stable_and_artifact_hash_changes_when_content_changes() -> None:
    site = create_site("render-hash")
    subnet = create_subnet(site)
    reservation = create_reservation(subnet)
    first_files = render_site_dnsmasq_config(site)
    first_manifest = build_artifact_manifest(site=site, version_number=1, rendered_files=first_files)
    first_hash = compute_artifact_hash(first_manifest)

    reservation.description = "Description does not render"
    reservation.full_clean()
    reservation.save()
    same_files = render_site_dnsmasq_config(site)
    same_manifest = build_artifact_manifest(site=site, version_number=1, rendered_files=same_files)

    reservation.hostname = "printer-renamed"
    reservation.full_clean()
    reservation.save()
    changed_files = render_site_dnsmasq_config(site)
    changed_manifest = build_artifact_manifest(site=site, version_number=1, rendered_files=changed_files)

    assert sha256_text(first_files["dnsmasq/30-reservations.conf"]) == first_manifest["files"][2]["sha256"]
    assert compute_artifact_hash(same_manifest) == first_hash
    assert compute_artifact_hash(changed_manifest) != first_hash
