from __future__ import annotations

import hashlib
import ipaddress
import json

from managed_dhcp_server.ipam.models import DHCPPool, DHCPReservation, IPv4Subnet, Site

RENDERER_VERSION = "0.1.0"
RENDERED_FILE_PATHS = [
    "dnsmasq/10-ranges.conf",
    "dnsmasq/20-options.conf",
    "dnsmasq/30-reservations.conf",
    "dnsmasq/40-hosts.conf",
]


def render_site_dnsmasq_config(site: Site) -> dict[str, str]:
    subnets = list(site.ipv4_subnets.all())
    subnets.sort(key=_subnet_sort_key)

    return {
        "dnsmasq/10-ranges.conf": _render_ranges(site, subnets),
        "dnsmasq/20-options.conf": _render_options(site, subnets),
        "dnsmasq/30-reservations.conf": _render_reservations(site, subnets),
        "dnsmasq/40-hosts.conf": _render_hosts(site, subnets),
    }


def build_artifact_manifest(*, site: Site, version_number: int, rendered_files: dict[str, str]) -> dict[str, object]:
    return {
        "schema": "config-artifact.v1",
        "site_id": str(site.id),
        "config_version": version_number,
        "renderer_version": RENDERER_VERSION,
        "target": {
            "backend": "dnsmasq",
            "min_agent_version": "0.1.0",
        },
        "files": [
            {"path": path, "sha256": sha256_text(rendered_files[path])}
            for path in sorted(rendered_files)
        ],
    }


def compute_artifact_hash(manifest: dict[str, object]) -> str:
    payload = json.dumps(manifest, sort_keys=True, separators=(",", ":"))
    return sha256_text(payload)


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _render_ranges(site: Site, subnets: list[IPv4Subnet]) -> str:
    lines = _header(site)
    pools = _enabled_pools(subnets)
    pools.sort(key=_pool_sort_key)

    for pool in pools:
        subnet = pool.subnet
        network = ipaddress.ip_network(subnet.cidr)
        lease_time = pool.lease_time_seconds or subnet.default_lease_time_seconds
        lines.append(
            f"dhcp-range=set:{_subnet_tag(subnet)},"
            f"{pool.start_ip},{pool.end_ip},{network.netmask},{lease_time}s"
        )

    return _join_lines(lines)


def _render_options(site: Site, subnets: list[IPv4Subnet]) -> str:
    lines = _header(site)
    for subnet in subnets:
        tag = _subnet_tag(subnet)
        if subnet.gateway:
            lines.append(f"dhcp-option=tag:{tag},option:router,{subnet.gateway}")
        if subnet.dns_servers:
            lines.append(f"dhcp-option=tag:{tag},option:dns-server,{','.join(subnet.dns_servers)}")
    return _join_lines(lines)


def _render_reservations(site: Site, subnets: list[IPv4Subnet]) -> str:
    lines = _header(site)
    reservations = _enabled_reservations(subnets)
    reservations.sort(key=_reservation_sort_key)

    for reservation in reservations:
        lines.append(
            f"dhcp-host={reservation.mac_address},set:{_subnet_tag(reservation.subnet)},"
            f"{reservation.ip_address},{reservation.hostname},infinite"
        )

    return _join_lines(lines)


def _render_hosts(site: Site, subnets: list[IPv4Subnet]) -> str:
    lines = _header(site)
    reservations = _enabled_reservations(subnets)
    reservations.sort(key=lambda reservation: (reservation.hostname, _ip_sort_key(reservation.ip_address), reservation.mac_address))

    for reservation in reservations:
        lines.append(f"address=/{reservation.hostname}/{reservation.ip_address}")

    return _join_lines(lines)


def _header(site: Site) -> list[str]:
    return [
        "# Generated by Managed DHCP/IPAM Control Plane.",
        "# Do not edit manually.",
        f"# Site: {site.slug}",
        "",
    ]


def _join_lines(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


def _enabled_pools(subnets: list[IPv4Subnet]) -> list[DHCPPool]:
    return [
        pool
        for subnet in subnets
        for pool in subnet.dhcp_pools.select_related("subnet").filter(enabled=True)
    ]


def _enabled_reservations(subnets: list[IPv4Subnet]) -> list[DHCPReservation]:
    return [
        reservation
        for subnet in subnets
        for reservation in subnet.dhcp_reservations.select_related("subnet").filter(enabled=True)
    ]


def _subnet_tag(subnet: IPv4Subnet) -> str:
    network = ipaddress.ip_network(subnet.cidr)
    return f"subnet-{str(network.network_address).replace('.', '-')}-{network.prefixlen}"


def _subnet_sort_key(subnet: IPv4Subnet) -> tuple[int, int, str]:
    network = ipaddress.ip_network(subnet.cidr)
    return (int(network.network_address), network.prefixlen, subnet.name)


def _pool_sort_key(pool: DHCPPool) -> tuple[int, int, str]:
    return (_ip_sort_key(pool.start_ip), _ip_sort_key(pool.end_ip), pool.name)


def _reservation_sort_key(reservation: DHCPReservation) -> tuple[int, str, str]:
    return (_ip_sort_key(reservation.ip_address), reservation.mac_address, reservation.hostname)


def _ip_sort_key(value: object) -> int:
    return int(ipaddress.ip_address(str(value)))
